### ISSUE TITLE
Progress on google play store

### ISSUE THREAD

**Issue by Jezternz** [sregg/spotify-tv#14]
Just wondering if there are plans to rebrand the app and get it on play store again? (I was about to start writing my own to play my own playlists when I came across this project)

**Comment by sregg** [comment]
Hi @Jezternz, I'm still waiting for Spotify to give me a consent document so I can update the app with the old logo.
(you can help me by commenting here: https://community.spotify.com/t5/Live-Ideas/Add-support-for-Android-TV/idi-p/951259/page/5#comments)

In the meantime, you can build this yourself and try it. If you want to participate in the development of the app, feel free to send me pull to requests.
