### ISSUE TITLE
Playlist does not show all playlists

### ISSUE THREAD

**Issue by NewJerseyGuy** [sregg/spotify-tv#17]

**Comment by Donaldini** [comment]
This is indeed a problem. You can get around the problem if you have access to a desktop installation of spotify and change the order of the playlist so your desired playlist is in the first 20 playlists.

Though it should really load all playlists.

**Comment by josh-burton** [comment]
This should have been fixed in the latest release with #24

**Comment by sregg** [comment]
Fixed in #24
