### ISSUE TITLE
Question: does it needs premium subscription?

### ISSUE THREAD

**Issue by albertogasparin** [sregg/spotify-tv#21]
As I'm looking for a way to remotely control Spotify on the nexus player, does this solution works even without a premium subscription?
Or is it like the official app (sideloaded requires premium subscription to allow Spotify connect)?

**Comment by sregg** [comment]
Yes it does require a premium account. This is unfortunately a limitation of the SDK

**Comment by sregg** [comment]
Yes it does require a premium account. This is unfortunately a limitation of the SDK
