### ISSUE TITLE
Can't update support library

### ISSUE THREAD

**Issue by josh-burton** [sregg/spotify-tv#29]
Updating the support library breaks the selection state for cards.

After some investigation it seems this is due to the SpotifyCardView. Any calls to load an image or change the imageview dimensions breaks the selection.

It is probably a better approach to extend BaseCardView and create our own CardView, rather than wrapping the CardView in another layout.

**Comment by sregg** [comment]
Good catch!
If you feel like it, you can go and fix that :)
